### ISSUE TITLE
not getting output 

### ISSUE THREAD

**Issue by saikiran994** [aufzayed/HydraRecon#1]
i am trying in windows10, its not giving output.
its showing errors
![Screenshot (208)](https://user-images.githubusercontent.com/37449869/89345210-b1043b00-d6c4-11ea-8393-1f711e4c27b8.png)

**Comment by aufzayed** [comment]
I am sorry man I didn't test it on windows I'll fix that and Sorry for the late reply

**Comment by aufzayed** [comment]
if you try it on linux it works better. it is designed for linux

**Comment by saikiran994** [comment]
if possible try to fix it soon. it will be help full to us. because lot many members are trying in windows only

**Comment by aufzayed** [comment]
just pushed a new update

**Comment by aufzayed** [comment]
note: the crowler results based on basic methoud result if you provide example.com to the basic recon method you must provide the same domain to the crawler
