### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by wizhardhacker1** [aufzayed/HydraRecon#2]
Traceback (most recent call last):
  File "hydrarecon.py", line 255, in <module>
    subdomain_enum(host, path_to_save)
  File "hydrarecon.py", line 134, in subdomain_enum
    for subdomain in itertools.chain(_cs, _crt, _dbo, _et, _ht, _tc, _tm, _us, _vt):
TypeError: 'NoneType' object is not iterabl

![image](https://user-images.githubusercontent.com/46620390/134290111-0102f64c-cf14-462d-b3e3-9c43cdf5655d.png)

**Comment by aufzayed** [comment]
I updated the tool and added 4 subdomains enumeration APIs, try it and tell me if you found any problem
